[package]
name = "gm_code"
version = "0.0.1"
authors = ["Jack Spira <jjspira@gmail.com>"]
edition = "2018"


[dependencies]
clap = "2.33.0"
bitflags = "1.1.0"
fnv = "1.0.6"
serde = { version = "1.0.98", features = ["derive"] }
toml = "0.5.2"
logos = "0.9.7"

[[bin]]
name = "gm_code"